on:
  push:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
    inputs:
      environmentselector:
        description: 'Environment selector'
        required: false
        default: 'default'

jobs:
  setup:
    name: Choose Secrets Environment Job
    runs-on: windows-latest
    steps:
      - id: setup
        name: Setup Environment Setp
        run: |
          $envSelector = "${{ github.event.inputs.environmentselector }}"
          Write-Host "Environment Selector: $envSelector Branch ${{ github.ref }}"
          if ($envSelector -eq '' -or $envSelector -eq 'default') {            
            if ('${{ github.ref }}' -eq 'refs/heads/main') { 
              "build_env=prod" >> $env:GITHUB_ENV              
            } else {
              "build_env=dev" >> $env:GITHUB_ENV
            }
          } else {
            "build_env=$envSelector" >> $env:GITHUB_ENV
          }
    outputs:
      build_env: ${{ env.build_env }}

  cd_deploy:
    name: Deploy Azure Environment
    needs: setup
    environment: ${{ needs.setup.outputs.build_env }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure CLI Login for ${{ needs.setup.outputs.build_env }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - id: resolve-vars
        name: Resolve variables
        run: .\deployment\ResolveVars.ps1 -BUILD_ENV ${{ needs.setup.outputs.build_env }}

      - name: Build azure environment
        id: build_az_env
        uses: azure/arm-deploy@v1
        with:
          deploymentName: '${{ needs.setup.outputs.build_env }}-${{ github.run_number }}'
          resourceGroupName: ${{ steps.resolve-vars.outputs.resourceGroupName }}
          template: ./deployment/deploy.bicep
          failOnStdErr: false
          parameters: >
            prefix=${{ steps.resolve-vars.outputs.prefix }}
            appInsightsName=${{ steps.resolve-vars.outputs.appInsightsName }}           
            appPlanName=${{ steps.resolve-vars.outputs.appPlanName }}
            appName=${{ steps.resolve-vars.outputs.appName }}
            appStorageName=${{ steps.resolve-vars.outputs.appStorageName }}
            appDatabaseName=${{ steps.resolve-vars.outputs.appDatabaseName }}
            appId=${{ steps.resolve-vars.outputs.appId }}
            appClientId=${{ steps.resolve-vars.outputs.appClientId }}
            apiKey=${{ steps.resolve-vars.outputs.apiKey }}
            allowedIPList=${{ steps.resolve-vars.outputs.allowedIPList }}
            sharedKeyVaultName=${{ steps.resolve-vars.outputs.sharedKeyVaultName }}
            appStorageConn=${{ steps.resolve-vars.outputs.appStorageConn }}

      - id: deploy
        name: Deploy code
        run: .\Deployment\Deploy.ps1 -ResourceGroupName ${{ steps.resolve-vars.outputs.resourceGroupName }} -AppName ${{ steps.build_az_env.outputs.funcName }}

      - name: Enable Smoke test flag
        run: |
          $AppName = "${{ steps.build_az_env.outputs.funcName }}"
          $ResourceGroupName = "${{ steps.resolve-vars.outputs.resourceGroupName }}"
          az functionapp config appsettings set --name $AppName --resource-group $ResourceGroupName --settings "SMOKE_TEST=true" -o none

      - id: smoke-test        
        name: Run Smoke test
        run: |
          $unitTestFilePath = "${{ env.RUNNER_TEMP }}\TestResults\unittests.xml"
          dotnet test -e X_URL=${{ env.base_url }} -e X_API_KEY=${{ steps.resolve-vars.outputs.apiKey }} --filter TestCategory=${{ needs.setup.outputs.build_env }} --logger "junit;LogFilePath=$unitTestFilePath"        

      - name: Disable Smoke test flag
        if: ${{ always() }}
        run: |
          $AppName = "${{ steps.build_az_env.outputs.funcName }}"
          $ResourceGroupName = "${{ steps.resolve-vars.outputs.resourceGroupName }}"
          az functionapp config appsettings set --name $AppName --resource-group $ResourceGroupName --settings "SMOKE_TEST=false" -o none

      - name: Publish test results
        if: ${{ always() }}
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        with:
          files: ${{ env.RUNNER_TEMP }}/TestResults/*.xml